

# Title
Preliminary development of an operating model for Peruvian common eel

# Subtitle
Common eel OM - data limited approach

# Author(s)
Bill Harford, Nature Analytics, 551 Lakeshore Rd E, Suite 105 Mississauga, ON, L5G 0A8, Canada
Report prepared for The Nature Conservancy

# Date
July 19, 2021

# Introduction
A preliminary demonstration of operating model (OM) building using the openMSE framework. This report and accompanying R code demonstrate the data-limited approach to building an OM for the common eel of Peru. The OM is developed with emphasis on fisheries operating near Tumbes, Peru.

# Stock Parameters

## Common_Name
No justification provided. 

## maxage
Maximum age was set a little higher than the maximum observed age of 14 years.

## R0
Scaling parameter set at arbitrary value.

## M
Natural mortality was specified for the range reported in the MSC pre-assessment SAI (2021).

## Msd
To address the possibility of M changing among years in these simulations we set a modest, arbitrary level of inter-annual variability with a lognormal CV of between 5% and 10% (i.e. 0.05 - 0.1), corresponding with 95% probability interval of +/-10% to +/- 20%. 

## h
Highly uncertain parameter. Given current emphasis on surplus production modeling, a wide range for steepness was specified over which the performance of SP models could be evaluated.

## SRrel
Beverton-Holt form assumed. 

## Perr
No estimates for recruitment variability were available at time of OM specification.
Bounds for this parameter were set to reflect highly variable recruitment. 

## AC
A wide range of values was used for auto-correlation in recruitment to reflect the uncertainty in this parameter.

## Linf
Used range reported by SAI (2021), based on studies that collected otoliths for age estimation. 

## Linfsd
Inter-annual variability unknown. Assumed up to 5%

## K
Used range reported by SAI (2021), based on studies that collected otoliths for age estimation.  

## Ksd
Inter-annual variability unknown. Assumed up to 5%

## t0
Used range reported by SAI (2021), based on studies that collected otoliths for age estimation. 

## LenCV
Unknown. Default values used.

## L50
Used range of values reported for geographies in proximity to Tumbes

## L50_95
Used range of values reported for geographies in proximity to Tumbes.

## D
Since the minimum size limit is within proximity to size at maturity, the 95% credible interval of relative vulnerable biomass from the stock assessment was used as a proxy for depletion range.  

## a
Chicaiza (2013, 2016) 

## b
Chicaiza (2013, 2016)

## Size_area_1
A mixed stock is assumed.

## Frac_area_1
A mixed stock is assumed.

## Prob_staying
A mixed stock is assumed

## Fdisc
The base-case model assumed no discarding and no discard mortality.

## Source


# Fleet Parameters

## nyears
Borrowed from: Generic_Increasing effort

## Spat_targ
Borrowed from: Generic_Increasing effort

## EffYears
Borrowed from: Generic_Increasing effort

## EffLower
Borrowed from: Generic_Increasing effort

## EffUpper
Borrowed from: Generic_Increasing effort

## Esd
Borrowed from: Generic_Increasing effort

## qinc
Borrowed from: Generic_Increasing effort

## qcv
Borrowed from: Generic_Increasing effort

## L5
Borrowed from: Generic_Increasing effort

## LFS
Borrowed from: Generic_Increasing effort

## Vmaxlen
Borrowed from: Generic_Increasing effort

## isRel
Borrowed from: Generic_Increasing effort

## LR5
Borrowed from: Generic_Increasing effort

## LFR
Borrowed from: Generic_Increasing effort

## Rmaxlen
Borrowed from: Generic_Increasing effort

## DR
Borrowed from: Generic_Increasing effort

## CurrentYr
Borrowed from: Generic_Increasing effort

## MPA
Borrowed from: Generic_Increasing effort



# Obs Parameters

## Cobs
Borrowed from: Precise-Unbiased

## Cbiascv
Borrowed from: Precise-Unbiased

## CAA_nsamp
Borrowed from: Precise-Unbiased

## CAA_ESS
Borrowed from: Precise-Unbiased

## CAL_nsamp
Borrowed from: Precise-Unbiased

## CAL_ESS
Borrowed from: Precise-Unbiased

## Iobs
Borrowed from: Precise-Unbiased

## Btobs
Borrowed from: Precise-Unbiased

## Btbiascv
Borrowed from: Precise-Unbiased

## beta
Borrowed from: Precise-Unbiased

## LenMbiascv
Borrowed from: Precise-Unbiased

## Mbiascv
Borrowed from: Precise-Unbiased

## Kbiascv
Borrowed from: Precise-Unbiased

## t0biascv
Borrowed from: Precise-Unbiased

## Linfbiascv
Borrowed from: Precise-Unbiased

## LFCbiascv
Borrowed from: Precise-Unbiased

## LFSbiascv
Borrowed from: Precise-Unbiased

## FMSY_Mbiascv
Borrowed from: Precise-Unbiased

## BMSY_B0biascv
Borrowed from: Precise-Unbiased

## Irefbiascv
Borrowed from: Precise-Unbiased

## Brefbiascv
Borrowed from: Precise-Unbiased

## Crefbiascv
Borrowed from: Precise-Unbiased

## Dbiascv
Borrowed from: Precise-Unbiased

## Dobs
Borrowed from: Precise-Unbiased

## hbiascv
Borrowed from: Precise-Unbiased

## Recbiascv
Borrowed from: Precise-Unbiased

## sigmaRbiascv
Borrowed from: Precise-Unbiased

## Eobs
Borrowed from: Precise-Unbiased

## Ebiascv
Borrowed from: Precise-Unbiased

# Imp Parameters

## TACFrac
Borrowed from: Perfect_Imp

## TACSD
Borrowed from: Perfect_Imp

## TAEFrac
Borrowed from: Perfect_Imp

## TAESD
Borrowed from: Perfect_Imp

## SizeLimFrac
Borrowed from: Perfect_Imp

## SizeLimSD
Borrowed from: Perfect_Imp



# References

Arancibia H, Alarcón L, Caballero R, Concha R, Carmona A. (2000) “Nuevas pesquerías para Chile Central. Anguila común (Ophichthus pacifici)”. Proyecto FONDEF D97I-1058. Desarrollo de nuevas pesquerías de recursos marinos bentónicos, pelágicos y demersales en Chile Central. Documento Téc- nico No3, UNITED, Departamento de Oceanografía, Universidad de Concepción, 20 pp. 

Castillo R (1991). “Análisis de la Pesca experimental del recurso anguila común (Ophichthus pacifici) en Paita durante 1991”. Informe laboratorio costero de Paita del IMARPE. 25 Pp.

Castillo R, Gómez E, Paredes F. (2000). “Pesquería y biología de la anguila común
Ophichthus pacifici (Günter) en el Perú.” Inf. Prog. Inst. Mar Perú. Dic. 134. 19 pp.

Chicaiza, D. (2005). “Principales aspectos Biológicos- Pesqueros de la anguila común (Ophichthus pacifici) (Valenciennes, 1839) durante Febrero 2004 - Marzo 2005.  Instituto Nacional de Pesca Proceso de Investigación de Recursos Bioacuáticos y su Ambiente. Guayaquil, Guayas, Ecuador: Ecuador.

Chicaiza D. (2013). “Pesca Industrial de anguila común (Ophichthus remiger) en el Golfo de Guayaquil–Ecuador: Análisis de algunos indicadores biológicos y pesqueros durante el seguimiento a la pesca piloto 2012.” Instituto Nacional de Pesca. Informe Técnico.

Chicaiza D. (2016). “Indicadores biológicos reproductivos de la Angila Común (Ophichthus remiger) y sus implicaciones en el manejo de la Pesca Industrial en el Golfo de Guayaquil” (Master's thesis). Universidad de Guayaquil

España N. (2015). “Incidencia de la talla en el desarrollo gonadal del recurso Ophichthus remiger (VALENCIENNES, 1842)”. Master's thesis, Faculty of Natural Sciences. University of Guayaquil, 2015.
FAO (May 2013) “La República Del Ecuador” Accessed: 10-May-2021 http://www.fao.org/fishery/facp/ECU/es

FOA (May 2014) “The Republic of Chile” Accessed: 10-May-2021
http://www.fao.org/fishery/facp/CHL/es

FAO (February 2019) “The Republic of Peru” Accessed: 10-May-2021 http://www.fao.org/fishery/facp/PER/es 
FAO (June 2019) “The Republic of Colombia” Accessed: 10-May-2021 http://www.fao.org/fishery/facp/COL/es 

INP Instituto Nacional de Pesca (2018) Anguilla Fishing File-RPG 022 http://www.institutopesca.gob.ec/wp-content/uploads/2018/01/FICHA-022-ANGUILA-RPG-1.pdf

INP Instituto Nacional de Pesca (2021) “Program: Monitoring of Artisanal Fishing Landings of Demersal Fish in the Main Ports of Ecuador” Accessed: 10-May-2021 http://www.institutopesca.gob.ec/pesca-artesanal/

IMARPE. Instituto del Mar de Perú. (2012) “Edad y crecimiento de Ophichthus remiger (Valenciennes) en el norte del mar peruano, 2004.” INSTITUTO DEL MAR DEL PERÚ INFORME ISSN 0378-7702 Volumen 39, Números 1-2 

IMARPE. Instituto del Mar de Perú. (Octubre-Diciembre de 2007). Informe, volumen 34,  número 4. “La anguila Ophichthus remiger en aguas de las Islas Lobos de Afuera, Lambayeque, durante el 2005."  INSTITUTO DEL MAR DEL PERÚ INFORME ISSN 0378-7702 Volumen 34, Número 4

IMARPE Instituto del Mar de Perú. (2020) Informe de la pesca exploratoria del recurso anguila Ophichthus remiger. R.M. N°402-2019-PRODUCE
Kjesbu OS, Holm JC. (1994). “Oocyte recruitment in first-time spawning Atlantic cod (Gadus morhua) in relation to feeding regime.” Can. J. Fish. Aquat. Sci. 51, 1893–1898.

Pauly D. (1983). “Some simple methods for the assessment of tropical fish stocks” (No. 234). Food & Agriculture Org. Rome.

PROMPEX – IMARPE. (2003). GERENCIA DE PROMOCIÓN DE MERCADOS DEL SECTOR PESCA Y ACUICULTURA. Breve Perfil, Bilológico Pesquero y Comercial de la Anguila. Perú, Perú. http://www.imarpe.pe/imarpe/archivos/articulos/imarpe/biblioteca/adj_perfil_anguila.pdf

Rust, Susanne (September 2020) “Tensions rise in Ecuador and Peru as Chinese fishing fleet moves south from Galapagos” Los Angeles Times. Accessed: 10-May-2021 https://www.latimes.com/environment/story/2020-09-23/tensions-rise-in-ecuador-and-peru-as-chinese-fishing-fleet-moves-south-from-galapagos
SAI Global (2021) “Pesca de Anguila Ophichthus remiger en el Norte  del Perú entre			 lasregiones de Tumbes a Piura.”

Schuhbauer (2006). “Fishery and population dynamics of the punctuated snake-eel, Ophichthus remiger, (Ophichthidae), North Perú.” Thesis. M.Sc. In International Studies in Aquatic Tropical Ecology. University of Bremen, Faculty for Biology & Chemistry. 63pp. 				
Vera M. (2004). “Distribución espacial y aspectos biológicos pesqueros de Ophichthus remiger “anguila común” en el litoral del departamento de Lambayeque (mayo 2002 – julio 2003)”. Tesis. Lic. Bio – Pesq. UNPRG. Lambayeque Perú. 89pp. 

Vera, M. (2006). Talla de la primera madurez y época de desove de "anguila común" O. remiger (Valenciennes, 1842) en el litoral de la región Tumbes. Tumbes-Instituto del mar del Perú.
Weatherley AH. Gill HS. (1987). “The biology of fish growth”. Academic Press, London pp 139-146

